version: '3.7'

services:
  api:
    image: arnebogaerts/api-basisproject:latest
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - SQLALCHEMY_DATABASE_URL=mysql://user:password@db:3306/cd_database

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cd_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
