on:
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -f Dockerfile -t cd-database-image .

    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Build
      run: docker build -t ${{ secrets.DOCKER_USER }}/python-api-test:latest .

    - name: Upload container to Docker Hub with Push
      run: docker push ${{ secrets.DOCKER_USER }}/python-api-test:latest
